import os
import shutil
import tempfile
import uuid

from fastapi import FastAPI, File, Form, HTTPException, UploadFile

from src.agents.pipeline_agent.pipeline_agent import run_pipeline_agent

from src.agents.testing_agent.testing_agent import run_testing_agent
from src.agents.testing_agent.graph import (
    node_prepare_metadata,
    node_reason_strategy,
    node_execute_sandbox,
    node_forensic_diagnosis,
    node_aggregate_results,
)

from src.agents.reporting_agent.reporting_agent import run_reporting_agent


app = FastAPI(
    title="AegisML API",
    description="AI-powered ML pipeline security auditing API.",
    version="1.0.0",
)


@app.get("/")
def root():
    return {
        "message": "AegisML API is running."
    }


def save_upload(
    uploaded_file: UploadFile,
    directory: str,
) -> str:
    """
    Save an uploaded file to a temporary directory.
    """

    file_path = os.path.join(
        directory,
        uploaded_file.filename,
    )

    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(
            uploaded_file.file,
            buffer,
        )

    return file_path


# =========================================================
# HITL AUDIT SESSION STORAGE
# =========================================================

# Local in-memory storage used between:
#
# Gate 1:
#   Agent 1 + attack planning
#
# and:
#
# Gate 1 approval:
#   Agent 2 execution + Agent 3 reporting
#
# This is suitable for the current local/demo architecture.
#
# For a production deployment this should later be replaced
# with persistent session storage such as Redis or a database.

AUDIT_SESSIONS = {}


# =========================================================
# COMMON HELPERS
# =========================================================

def _validate_upload_types(
    pipeline_file: UploadFile,
    model_file: UploadFile,
    dataset_file: UploadFile,
) -> None:
    """
    Validate the three artifacts required by AegisML.
    """

    if not pipeline_file.filename.endswith(".py"):
        raise HTTPException(
            status_code=400,
            detail="Pipeline must be a Python (.py) file.",
        )

    if not model_file.filename.endswith(".pkl"):
        raise HTTPException(
            status_code=400,
            detail="Model must be a pickle (.pkl) file.",
        )

    if not dataset_file.filename.endswith(".csv"):
        raise HTTPException(
            status_code=400,
            detail="Dataset must be a CSV (.csv) file.",
        )


def _deployment_context(
    agent_1_result,
):
    """
    Extract the pipeline-specific deployment context
    generated by Agent 1.
    """

    return (
        agent_1_result
        .get(
            "threat_model",
            {},
        )
        .get(
            "deployment_context",
            {},
        )
        or {}
    )


def _execute_agent_2_with_approved_plan(
    session,
):
    """
    Continue Agent 2 after Gate 1 approval.

    The planning stages have already been completed before
    the human approval gate, so execution starts directly
    from the approved attack strategy.
    """

    state = {
        "agent_1_results": session[
            "agent_1_result"
        ],

        "model_path": session[
            "model_path"
        ],

        "dataset_path": session[
            "dataset_path"
        ],

        "pipeline_path": session[
            "pipeline_path"
        ],

        "text_column": session[
            "text_column"
        ],

        "label_column": session[
            "label_column"
        ],

        "vectorizer_path": None,

        "test_targets": None,

        "dataset_profile": session.get(
            "dataset_profile",
            {},
        ),

        "attack_strategy_plan": session[
            "attack_strategy_plan"
        ],

        "planned_tests": session[
            "attack_strategy_plan"
        ].get(
            "selected_tests",
            [],
        ),

        "execution_plan_log": (
            list(
                session.get(
                    "execution_plan_log",
                    [],
                )
            )
            + [
                (
                    "Gate 1 approved by human reviewer. "
                    "Proceeding with approved attack strategy."
                )
            ]
        ),

        "status": "gate_1_approved",
    }

    # -----------------------------------------------------
    # Agent 2 - execute the approved plan
    # -----------------------------------------------------

    for node_function in (
        node_execute_sandbox,
        node_forensic_diagnosis,
        node_aggregate_results,
    ):

        update = node_function(
            state
        ) or {}

        state.update(
            update
        )

    return state


# =========================================================
# HITL GATE 1
# AUDIT PLANNING ENDPOINT
# =========================================================

@app.post("/audit/plan")
def plan_audit(
    pipeline_file: UploadFile = File(...),
    model_file: UploadFile = File(...),
    dataset_file: UploadFile = File(...),
    text_column: str = Form("text"),
    label_column: str = Form("label"),
):
    """
    Run Agent 1 and the Agent 2 planning stage.

    Execution stops before any dynamic attacks are launched.

    The generated attack strategy is returned to the user
    for explicit human approval at Gate 1.
    """

    _validate_upload_types(
        pipeline_file,
        model_file,
        dataset_file,
    )

    # A normal TemporaryDirectory cannot be used here because
    # the uploaded artifacts must survive between /audit/plan
    # and /audit/execute.

    temp_dir = tempfile.mkdtemp(
        prefix="aegisml_hitl_"
    )

    try:

        # -------------------------------------------------
        # Save uploaded artifacts
        # -------------------------------------------------

        pipeline_path = save_upload(
            pipeline_file,
            temp_dir,
        )

        model_path = save_upload(
            model_file,
            temp_dir,
        )

        dataset_path = save_upload(
            dataset_file,
            temp_dir,
        )

        # -------------------------------------------------
        # Read source code
        # -------------------------------------------------

        with open(
            pipeline_path,
            "r",
            encoding="utf-8",
        ) as file:

            python_code = file.read()

        # -------------------------------------------------
        # Agent 1
        # Pipeline & Threat Model Agent
        # -------------------------------------------------

        agent_1_result = run_pipeline_agent(
            python_code
        )

        # -------------------------------------------------
        # Agent 2
        # Planning only
        # -------------------------------------------------

        planning_state = {
            "agent_1_results": (
                agent_1_result
            ),

            "dataset_path": (
                dataset_path
            ),

            "model_path": (
                model_path
            ),

            "pipeline_path": (
                pipeline_path
            ),

            "text_column": (
                text_column
            ),

            "label_column": (
                label_column
            ),

            "vectorizer_path": None,

            "test_targets": None,

            "execution_plan_log": [],
        }

        # Prepare dataset/model metadata before reasoning
        # about the attack strategy.

        metadata_update = (
            node_prepare_metadata(
                planning_state
            )
            or {}
        )

        planning_state.update(
            metadata_update
        )

        # Generate the attack strategy but DO NOT execute it.

        strategy_update = (
            node_reason_strategy(
                planning_state
            )
            or {}
        )

        planning_state.update(
            strategy_update
        )

        # -------------------------------------------------
        # Create persistent Gate 1 session
        # -------------------------------------------------

        audit_id = (
            uuid.uuid4().hex
        )

        AUDIT_SESSIONS[
            audit_id
        ] = {
            "temp_dir": (
                temp_dir
            ),

            "pipeline_path": (
                pipeline_path
            ),

            "model_path": (
                model_path
            ),

            "dataset_path": (
                dataset_path
            ),

            "text_column": (
                text_column
            ),

            "label_column": (
                label_column
            ),

            "pipeline_source": (
                python_code
            ),

            "agent_1_result": (
                agent_1_result
            ),

            "dataset_profile": (
                planning_state.get(
                    "dataset_profile",
                    {},
                )
            ),

            "attack_strategy_plan": (
                planning_state.get(
                    "attack_strategy_plan",
                    {},
                )
            ),

            "execution_plan_log": (
                planning_state.get(
                    "execution_plan_log",
                    [],
                )
            ),
        }

        # -------------------------------------------------
        # Return Gate 1 information
        # -------------------------------------------------

        return {
            "status": (
                "awaiting_gate_1"
            ),

            "audit_id": (
                audit_id
            ),

            "attack_strategy_plan": (
                planning_state.get(
                    "attack_strategy_plan",
                    {},
                )
            ),

            "pipeline_graph": (
                agent_1_result.get(
                    "pipeline_graph",
                    {},
                )
            ),

            "pipeline_source": (
                python_code
            ),

            "vulnerability_findings": (
                agent_1_result.get(
                    "vulnerability_findings",
                    {},
                )
            ),

            "deployment_context": (
                _deployment_context(
                    agent_1_result
                )
            ),
        }

    except HTTPException:

        shutil.rmtree(
            temp_dir,
            ignore_errors=True,
        )

        raise

    except Exception as exc:

        shutil.rmtree(
            temp_dir,
            ignore_errors=True,
        )

        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )


# =========================================================
# HITL GATE 1 APPROVAL
# EXECUTION ENDPOINT
# =========================================================

@app.post("/audit/execute")
def execute_planned_audit(
    audit_id: str = Form(...),
):
    """
    Continue the audit after explicit human approval.

    This endpoint executes the attack strategy prepared by
    /audit/plan and then invokes Agent 3.

    The resulting report is returned with status
    awaiting_gate_2 so the UI can require a final
    human report sign-off before download.
    """

    session = AUDIT_SESSIONS.get(
        audit_id
    )

    if not session:

        raise HTTPException(
            status_code=404,
            detail=(
                "Audit planning session "
                "not found or expired."
            ),
        )

    try:

        # -------------------------------------------------
        # Agent 2
        # Execute human-approved strategy
        # -------------------------------------------------

        agent_2_result = (
            _execute_agent_2_with_approved_plan(
                session
            )
        )

        # -------------------------------------------------
        # Agent 3
        # Risk Scoring & Reporting Agent
        # -------------------------------------------------

        reporting_result = (
            run_reporting_agent(
                agent_1_results=(
                    session[
                        "agent_1_result"
                    ]
                ),
                agent_2_results=(
                    agent_2_result
                ),
            )
        )

        # -------------------------------------------------
        # Return result for Gate 2 review
        # -------------------------------------------------

        return {
            "status": (
                "awaiting_gate_2"
            ),

            "audit_id": (
                audit_id
            ),

            "report": (
                reporting_result.get(
                    "final_report"
                )
            ),

            "deployment_context": (
                _deployment_context(
                    session[
                        "agent_1_result"
                    ]
                )
            ),

            "pipeline_graph": (
                session[
                    "agent_1_result"
                ].get(
                    "pipeline_graph",
                    {},
                )
            ),

            "pipeline_source": (
                session[
                    "pipeline_source"
                ]
            ),

            "attack_strategy_plan": (
                session[
                    "attack_strategy_plan"
                ]
            ),
        }

    except HTTPException:
        raise

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )

    finally:

        # Remove uploaded files after the dynamic audit
        # and final report have been generated.

        shutil.rmtree(
            session.get(
                "temp_dir",
                "",
            ),
            ignore_errors=True,
        )

        AUDIT_SESSIONS.pop(
            audit_id,
            None,
        )


# =========================================================
# LEGACY / FULL-AUDIT ENDPOINT
# =========================================================

@app.post("/audit")
def run_audit(
    pipeline_file: UploadFile = File(...),
    model_file: UploadFile = File(...),
    dataset_file: UploadFile = File(...),
    text_column: str = Form("text"),
    label_column: str = Form("label"),
):
    """
    Run the complete AegisML security audit without
    stopping at the human approval gates.

    This endpoint is retained for compatibility.

    The Streamlit HITL workflow uses:
        /audit/plan
        /audit/execute
    """

    # -----------------------------------------------------
    # Validate uploaded file types
    # -----------------------------------------------------

    _validate_upload_types(
        pipeline_file,
        model_file,
        dataset_file,
    )

    try:

        # Create a temporary directory for uploaded files.

        with tempfile.TemporaryDirectory() as temp_dir:

            pipeline_path = save_upload(
                pipeline_file,
                temp_dir,
            )

            model_path = save_upload(
                model_file,
                temp_dir,
            )

            dataset_path = save_upload(
                dataset_file,
                temp_dir,
            )

            # -------------------------------------------------
            # Read pipeline source code
            # -------------------------------------------------

            with open(
                pipeline_path,
                "r",
                encoding="utf-8",
            ) as file:

                python_code = (
                    file.read()
                )

            # -------------------------------------------------
            # Agent 1
            # Pipeline & Threat Model Agent
            # -------------------------------------------------

            agent_1_result = (
                run_pipeline_agent(
                    python_code
                )
            )

            # -------------------------------------------------
            # Agent 2
            # Vulnerability Testing Agent
            # -------------------------------------------------

            agent_2_result = (
                run_testing_agent(
                    agent_1_results=(
                        agent_1_result
                    ),
                    model_path=(
                        model_path
                    ),
                    dataset_path=(
                        dataset_path
                    ),
                    pipeline_path=(
                        pipeline_path
                    ),
                    text_column=(
                        text_column
                    ),
                    label_column=(
                        label_column
                    ),
                )
            )

            # -------------------------------------------------
            # Agent 3
            # Reporting Agent
            # -------------------------------------------------

            reporting_result = (
                run_reporting_agent(
                    agent_1_results=(
                        agent_1_result
                    ),
                    agent_2_results=(
                        agent_2_result
                    ),
                )
            )

            # -------------------------------------------------
            # Deployment context
            # -------------------------------------------------

            deployment_context = (
                _deployment_context(
                    agent_1_result
                )
            )

            # -------------------------------------------------
            # Return full result
            # -------------------------------------------------

            return {
                "status": (
                    "completed"
                ),

                "report": (
                    reporting_result.get(
                        "final_report"
                    )
                ),

                "deployment_context": (
                    deployment_context
                ),

                "pipeline_graph": (
                    agent_1_result.get(
                        "pipeline_graph",
                        {},
                    )
                ),

                "pipeline_source": (
                    python_code
                ),

                "attack_strategy_plan": (
                    agent_2_result.get(
                        "attack_strategy_plan"
                    )
                    or (
                        agent_2_result.get(
                            "structured_test_results"
                        )
                        or {}
                    ).get(
                        "attack_strategy_plan"
                    )
                    or {}
                ),
            }

    except HTTPException:
        raise

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail=str(exc),
        )