from typing import TypedDict, Any, Dict, Optional, List


class PipelineAgentState(TypedDict, total=False):
    """
    Internal state for Agent 1 (Pipeline & Threat Modeling Agent).
    Maintains code artifacts, extracted topological graphs, intermediate LLM
    reasoning outputs, and validation feedback used in self-correction loops.
    """
    # Core input
    code: str

    # Intermediate artifacts generated by tools
    pipeline_graph: Dict[str, Any]
    networkx_graph: Any
    graph_topology: Dict[str, Any]

    # Validated security outputs
    threat_model: Dict[str, Any]
    vulnerability_findings: Dict[str, Any]

    # Optional integration slot for future Agent 2 test results
    testing_agent_results: Optional[Dict[str, Any]]

    # Agent reflection and self-correction tracking
    validation_errors: Optional[str]
    retry_count: int
    max_retries: int
    status: str
